version: "3.9"

volumes:
  dbdata:

services :
  db:
    image: postgres
    environment:
      POSTGRES_PASSWORD: changeme
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - "dbdata:/var/lib/postgresql/data"
  admin:
    image: adminer
    ports:
      - 8080:8080
